name: Deploy
on:
  workflow_dispatch: # Ahora solo se activará cuando tú presiones el botón manualmente en GitHub

jobs:
  build:
    name: Build & Submit (Android)
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Checkout
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: ⚙️ Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci --legacy-peer-deps

      - name: 🚀 Build APK (Android)
        run: eas build --platform android --profile preview --non-interactive
